services:
  deepracer_1:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5000:5000"
      - "8888:8888"
    command: /bin/bash

  deepracer_2:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5001:5000"
      - "8889:8888"
    command: /bin/bash

  deepracer_3:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5003:5000"
      - "8890:8888"
    command: /bin/bash

  deepracer_4:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5004:5000"
      - "8891:8888"
    command: /bin/bash

  deepracer_5:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5005:5000"
      - "8892:8888"
    command: /bin/bash

  deepracer_6:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5006:5000"
      - "8893:8888"
    command: /bin/bash

  deepracer_7:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5007:5000"
      - "8894:8888"
    command: /bin/bash

  deepracer_8:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5008:5000"
      - "8895:8888"
    command: /bin/bash

  deepracer_9:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5009:5000"
      - "8896:8888"
    command: /bin/bash

  deepracer_10:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5010:5000"
      - "8897:8888"
    command: /bin/bash

  deepracer_11:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5011:5000"
      - "8898:8888"
    command: /bin/bash

  deepracer_12:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5012:5000"
      - "8899:8888"
    command: /bin/bash

  deepracer_13:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5013:5000"
      - "8900:8888"
    command: /bin/bash

  deepracer_14:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5014:5000"
      - "8901:8888"
    command: /bin/bash

  deepracer_15:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5015:5000"
      - "8902:8888"
    command: /bin/bash

  deepracer_16:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5016:5000"
      - "8903:8888"
    command: /bin/bash

  deepracer_17:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5017:5000"
      - "8904:8888"
    command: /bin/bash

  deepracer_18:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5018:5000"
      - "8905:8888"
    command: /bin/bash

  deepracer_19:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5019:5000"
      - "8906:8888"
    command: /bin/bash

  deepracer_20:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5020:5000"
      - "8907:8888"
    command: /bin/bash

  deepracer_21:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5021:5000"
      - "8908:8888"
    command: /bin/bash

  deepracer_22:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5022:5000"
      - "8909:8888"
    command: /bin/bash

  deepracer_23:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5023:5000"
      - "8910:8888"
    command: /bin/bash

  deepracer_24:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5024:5000"
      - "8911:8888"
    command: /bin/bash

  deepracer_25:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5025:5000"
      - "8912:8888"
    command: /bin/bash

  deepracer_26:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5026:5000"
      - "8913:8888"
    command: /bin/bash

  deepracer_27:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5027:5000"
      - "8914:8888"
    command: /bin/bash

  deepracer_28:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5028:5000"
      - "8915:8888"
    command: /bin/bash

  deepracer_29:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5029:5000"
      - "8916:8888"
    command: /bin/bash

  deepracer_30:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5030:5000"
      - "8917:8888"
    command: /bin/bash

  deepracer_31:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5031:5000"
      - "8918:8888"
    command: /bin/bash

  deepracer_32:
    image: aicrowd/base-images:deepracer_round1_release
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g
    ports:
      #- "5032:5000"
      - "8919:8888"
    command: /bin/bash

  # deepracer_33:
  #   image: aicrowd/base-images:deepracer_round1_release
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: 3
  #         memory: 6g
  #   ports:
  #     #- "5033:5000"
  #     - "8920:8888"

  # deepracer_34:
  #   image: aicrowd/base-images:deepracer_round1_release
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: 3
  #         memory: 6g
  #   ports:
  #     #- "5034:5000"
  #     - "8921:8888"

  # deepracer_35:
  #   image: aicrowd/base-images:deepracer_round1_release
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: 3
  #         memory: 6g
  #   ports:
  #     #- "5033:5000"
  #     - "8922:8888"

  # deepracer_36:
  #   image: aicrowd/base-images:deepracer_round1_release
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: 3
  #         memory: 6g
  #   ports:
  #     #- "5034:5000"
  #     - "8923:8888"